// <auto-generated />
using System;
using BasicASPTutorial.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasicASPTutorial.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250514100524_createStudentDb")]
    partial class createStudentDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasicASPTutorial.Modals.Student", b =>
                {
                    b.Property<int>("Student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Student_Id"));

                    b.Property<DateTime>("Student_Cr_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Student_Score")
                        .HasColumnType("integer");

                    b.HasKey("Student_Id");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
